photo_magic_server/config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users

  root to: 'public#index'
  resources :public
  resource :token

end

photo_magic_server/app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :uploaded_image,:default_url => "/system/images/uploaded_images/missing.png"
  validates_attachment_content_type :uploaded_image, :content_type => /\Aimage\/.*\Z/
end

photo_magic_server/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

photo_magic_server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

photo_magic_server/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def new 
    @image = Image.new
  end

  def create
    @image = Image.create(image_params)
    @images = Image.all
    render 'index'
  end

  def destroy
    @image = Image.find(image_params)
    @image.destroy
  end

  private 
    def image_params
      params.require(:image).permit(:uploaded_image, :description)
    end
end

photo_magic_server/app/controllers/public_controller.rb
class PublicController < ApplicationController
  acts_as_token_authentication_handler_for User
  #before_action :authenticate_user!
  def index
    @images = Image.all
    responde = @images.map {|i| {description: i.description, photo_url: i.uploaded_image.url}}
    respond_to do |format|
      format.html
      format.json {render json: responde, status: :ok}
    end
  end
end

photo_magic_server/app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  skip_before_filter :verify_authenticity_token
  respond_to :json
  def create
    email = params[:email]
    password = params[:password]
    if request.format != :json
        render :status=>406, :json=>{:message=>"The request must be json"}
        return
       end
 
    if email.nil? or password.nil?
       render :status=>400,
              :json=>{:message=>"The request must contain the user email and password."}
       return
    end
 
    @user=User.find_by_email(email.downcase)
 
    if @user.nil?
      logger.info("User #{email} failed signin, user cannot be found.")
      render :status=>401, :json=>{:message=>"Invalid email or passoword."}
      return
    end
 
 
    if not @user.valid_password?(password)
      logger.info("User #{email} failed signin, password \"#{password}\" is invalid")
      render :status=>401, :json=>{:message=>"Invalid email or password."}
    else
      render :status=>200, :json=>{:token=>@user.authentication_token}
    end

  end
  
  def destroy
    @user=User.find_by_authentication_token(params[:id])
    if @user.nil?
      logger.info("Token not found.")
      render :status=>404, :json=>{:message=>"Invalid token."}
    else
      @user.reset_authentication_token!
      render :status=>200, :json=>{:token=>params[:id]}
    end
  end

  def show 
    render json: {:message=>"Just show method"}
  end

end

photo_magic_server/app/helpers/application_helper.rb
module ApplicationHelper
end

photo_magic_server/app/helpers/images_helper.rb
module ImagesHelper
end

photo_magic_server/app/helpers/public_helper.rb
module PublicHelper
end

photo_magic_server/app/helpers/tokens_helper.rb
module TokensHelper
end

photo_magic_server/app/views/images/_form.html.erb
<div class="row">
  <div class="span4 offset4 well">
    <%= form_for @image, html: {multipart: true} do |f| %>
      <h4>Description</h4>
      <%= f.text_field :description %></br>
      <%= f.file_field :uploaded_image %>
      <p><%= f.submit :class => "btn btn-primary" %></p>
    <% end %>
    <div class='btn'><%= link_to "Back to List", images_path %></div>

  </div>
</div>
  

photo_magic_server/app/views/images/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @image %> |
  <%= link_to "View All", images_path %>
</p>

photo_magic_server/app/views/images/index.html.erb
<table>
  <div class="row">
    <div class="span6 offset3">
      <% for image in @images %>
        <div class="well">
          <%= image_tag image.uploaded_image.url,height: '500', width: '500' %>
          <h2><%= image.description %></h2>
        </div>
      <% end %>
      <div class="btn"><%= link_to "New Image", new_image_path %></div></br>
      <div class="btn btn-alert"><%= link_to "Log out",destroy_user_session_path, method: "DELETE"%></div>
    </div>
  </div>
</table>

photo_magic_server/app/views/images/new.html.erb
    <%= render 'form' %>

photo_magic_server/app/views/images/show.html.erb
<p>
  <%= image_tag @user.avatar.url %>
  <%= image_tag @user.avatar.url(:medium) %>
  <%= image_tag @user.avatar.url(:thumb) %>
</p>

<p>
  <%= link_to "Edit", edit_image_path(@image) %> |
  <%= link_to "Destroy", @image, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", images_path %>
</p>

photo_magic_server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhotoMagicServer" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">

            <%= bootstrap_flash %>
            <%= yield %>

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>